// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `npx prisma dev` imprime as duas URLs quando sobe: a de shadow database
    // usa a MESMA porta base só que +1 (ex: 51214 -> 51215), não um nome de
    // banco diferente na mesma porta — copie o valor de SHADOW_DATABASE_URL
    // exibido no terminal do `npx prisma dev` pro seu .env.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
